// This file was generated by gen_memset.rb and should not be edited by hand.

// Copyright (c) 2018 Sung Pae <self@sungpae.com>
// Distributed under the MIT license.
// http://www.opensource.org/licenses/mit-license.php

// +build !amd64

#include "textflag.h"

// func Int(s []int, n int)
TEXT ·Int(SB), NOSPLIT, $0
	JMP ·_Int(SB)

// func Int8(s []int8, n int8)
TEXT ·Int8(SB), NOSPLIT, $0
	JMP ·_Int8(SB)

// func Int16(s []int16, n int16)
TEXT ·Int16(SB), NOSPLIT, $0
	JMP ·_Int16(SB)

// func Int32(s []int32, n int32)
TEXT ·Int32(SB), NOSPLIT, $0
	JMP ·_Int32(SB)

// func Int64(s []int64, n int64)
TEXT ·Int64(SB), NOSPLIT, $0
	JMP ·_Int64(SB)

// func Uint(s []uint, n uint)
TEXT ·Uint(SB), NOSPLIT, $0
	JMP ·_Uint(SB)

// func Byte(s []byte, n byte)
TEXT ·Byte(SB), NOSPLIT, $0
	JMP ·_Byte(SB)

// func Uint16(s []uint16, n uint16)
TEXT ·Uint16(SB), NOSPLIT, $0
	JMP ·_Uint16(SB)

// func Uint32(s []uint32, n uint32)
TEXT ·Uint32(SB), NOSPLIT, $0
	JMP ·_Uint32(SB)

// func Uint64(s []uint64, n uint64)
TEXT ·Uint64(SB), NOSPLIT, $0
	JMP ·_Uint64(SB)

// func Uintptr(s []uintptr, n uintptr)
TEXT ·Uintptr(SB), NOSPLIT, $0
	JMP ·_Uintptr(SB)

// func Float32(s []float32, n float32)
TEXT ·Float32(SB), NOSPLIT, $0
	JMP ·_Float32(SB)

// func Float64(s []float64, n float64)
TEXT ·Float64(SB), NOSPLIT, $0
	JMP ·_Float64(SB)
