// This file was generated by gen_memset.rb and should not be edited by hand.

// Copyright (c) 2018 Sung Pae <self@sungpae.com>
// Distributed under the MIT license.
// http://www.opensource.org/licenses/mit-license.php

#include "textflag.h"

// func MemsetIntSlice(s []int, n int)
TEXT ·MemsetIntSlice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVQ n+24(FP), AX
	REP
	STOSQ               // memset(data, n, len)
	RET

// func MemsetInt8Slice(s []int8, n int8)
TEXT ·MemsetInt8Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVB n+24(FP), AX
	REP
	STOSB               // memset(data, n, len)
	RET

// func MemsetInt16Slice(s []int16, n int16)
TEXT ·MemsetInt16Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVW n+24(FP), AX
	REP
	STOSW               // memset(data, n, len)
	RET

// func MemsetInt32Slice(s []int32, n int32)
TEXT ·MemsetInt32Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVL n+24(FP), AX
	REP
	STOSL               // memset(data, n, len)
	RET

// func MemsetInt64Slice(s []int64, n int64)
TEXT ·MemsetInt64Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVQ n+24(FP), AX
	REP
	STOSQ               // memset(data, n, len)
	RET

// func MemsetUintSlice(s []uint, n uint)
TEXT ·MemsetUintSlice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVQ n+24(FP), AX
	REP
	STOSQ               // memset(data, n, len)
	RET

// func MemsetByteSlice(s []byte, n byte)
TEXT ·MemsetByteSlice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVB n+24(FP), AX
	REP
	STOSB               // memset(data, n, len)
	RET

// func MemsetUint16Slice(s []uint16, n uint16)
TEXT ·MemsetUint16Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVW n+24(FP), AX
	REP
	STOSW               // memset(data, n, len)
	RET

// func MemsetUint32Slice(s []uint32, n uint32)
TEXT ·MemsetUint32Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVL n+24(FP), AX
	REP
	STOSL               // memset(data, n, len)
	RET

// func MemsetUint64Slice(s []uint64, n uint64)
TEXT ·MemsetUint64Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVQ n+24(FP), AX
	REP
	STOSQ               // memset(data, n, len)
	RET

// func MemsetUintptrSlice(s []uintptr, n uintptr)
TEXT ·MemsetUintptrSlice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVQ n+24(FP), AX
	REP
	STOSQ               // memset(data, n, len)
	RET

// func MemsetFloat32Slice(s []float32, n float32)
TEXT ·MemsetFloat32Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVL n+24(FP), AX
	REP
	STOSL               // memset(data, n, len)
	RET

// func MemsetFloat64Slice(s []float64, n float64)
TEXT ·MemsetFloat64Slice(SB), NOSPLIT, $0
	MOVQ data+0(FP), DI
	MOVQ len+8(FP), CX
	MOVQ n+24(FP), AX
	REP
	STOSQ               // memset(data, n, len)
	RET
